const EmployeeData = `{
    teams{
        data{
          id
          attributes{
            firstName
            lastName
           resume{
            data{
              attributes{
                url
              }
            }
           }
           avatar{
            data{
              id
              attributes{
                url
              }
            }
          }
          }
        }
        data{
          id
          attributes{
            technology{
              id
              technology{
                data{
                  id
                  attributes{
                    name
                  }
                }
              }
              proficiency
            }
          }
        }
        data{
          id
          attributes{
            certification{
              id
              name
              issuingOrganization
              credentialURL
              logo{
                data{
                  attributes{
                    name
                  }
                }
              }
              neverExpire
              issueDate
            }
          }
        } 
        data{
          id
          attributes{
            projects{
              id
              projectName
              role
              description
              categories{
                data{
                  id
                  attributes{
                    title
                    description
                    icon{
                      data{
                        attributes{
                          url
                        }
                      }
                    }
                  }
                }
              }
              
             technologies{
              data{
                id
                attributes{
                  name 
                }
              }
            }
              
            }
          }
        }
        data{
          id
          attributes{
            education{
              id
              school
              degree
            }
          }
        }
        data{
          id
          attributes{
            experience{
              id
              Title
              employeeType
              companyName
              location
              startDate
              endDate
              industry
              description
            }
          }
        }
      }
}`;

export default EmployeeData;
