const TeamQuery = `{
    teams{
      data{
        id
        attributes{
          firstName
          lastName
          
          education{
            id
            school
            degree
            fieldOfStudy
            startDate
            endDate
            grade
            extraActivity 
          }
         experience{
          id
          Title
          employeeType
          companyName
          location
          startDate
          endDate
          industry
          description
          technologies{
            data{
              attributes{
                name
                link      
              }
            }
          }
        }
          certification{
            id
            name
            issuingOrganization
             neverExpire
            issueDate
            expireDate
            credentialID
            credentialURL          
          }
          resume{
            data{
              attributes{
                name
                alternativeText
              }
            }
          }
          avatar{
            data{
              attributes{
                name
                url
                alternativeText          
              }
            }
          }
          technology{
            id
           technology{
            data{
              attributes{
                name
                link
              }
            }
          }
            proficiency
          }
          
        }
      }
    }
  }`;

export default teamQuery;
