const AboutQuery = `
{
    aboutBanner{
      id
      header{
        id
        title
        description
      }
      buttonText{
        id 
        buttonText
        link
      }
    }
    aboutSuccess{
      id
      heading{
        id 
        title
        description
      }
      success{
        id
        number
        title
        description
      }
    }
    aboutMission{
      id
      mission{
        id
        image{
          url
        }
        title
        description
      }
    }
    aboutValue{
      id 
      heading{
        title
        description
      }
      valueCard{
        id
        title
        description
        icon{
          url
        }
      }
    }
    aboutTeacher{
      id
      heading{
        id
        title
        description
      }
      buttonText{
        id
        buttonText
        link
      }
      teachers{
        id
        firstName
        lastName
        description
        image{
          url
        }
        socialMedia{
          id 
          title
          link
        }
        jobTitle
      }
    }
    aboutHistory{
      id
      heading{
        id
        title
        description
      }
      buttonText{
        id
        link
        buttonText
      }
      timeline{
        id
        number
        title
        description
      }
    }
    aboutOffice{
      id
      heading{
        id
        title
        description
      }
      mapImage{
        url
      }
      officeCard{
        id
        country
        mail
        mailLink
        phone 
        phoneLink
        address
        addressLink
        icon{
          url
        }
      }
    }
  }
`;

export default AboutQuery;
