const DevelopmentQuery = `{
    developmentBanner{
      imageUrl
    }
    serviecesSection{
      title
      services{
        title
        shortDescription
        image
      }
    }
    projectsSection{
      title
      projects{
        title
        shortDescription 
        image
      }
    }
    clientsTestimonialsSection{
      title
      clients_testimonials{
        image
        clientName
        description
      }
    }
  }`;
