const developmentAboutQuery = `{
    developmentAboutPage{
      id
      heading{
        title
        description
      }
      successTitle
      success{
        number
        title
        description
      }
      ourStory{
        image
        title
        description
      }
      ourTeam{
        id
        heading{
          title
          description
        }
        joinOurTeam{
          buttonText
          link
        }
        teamMembers{
          id
          image
          title
          designation
        }
      }
      workValues{
        title
        description
      }
      workFlow{
        icon
        title
        description
      }
    }
    aboutHistory{
        id
        heading{
          id
          title
          description
        }
        buttonText{
          id
          link
          buttonText
        }
        timeline{
          id
          number
          title
          description
        }
      }
      aboutOffice{
        id
        heading{
          id
          title
          description
        }
        mapImage{
          url
        }
        officeCard{
          id
          country
          mail
          mailLink
          phone 
          phoneLink
          address
          addressLink
          icon{
            url
          }
        }
  }`;
export default developmentAboutQuery;
