import Industry from "@components/Industry";
import CourseSection from "@components/PageSections/CourseSection";
import Head from "next/head";
// import CourseSection from "../components/PageSections/CourseSection";
// import Footer from "../components/Footer";
import Footer from "../components/Footer";
import Features from "../components/PageSections/Features";
import HomeSection from "../components/PageSections/HomeSection";
// import Button from "../components/Button";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Button /> */}
        {/* <Features /> */}
        <HomeSection />
        <CourseSection />
        <Industry />
        {/* <Footer /> */}
        <Features />
        <Footer />
      </main>
    </div>
  );
}
